config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"
  resources :users, only: %i[new create show edit update]
  resources :sessions, only: %i[new create destroy]
  resources :pictures do
    collection { post :confirm }
  end
  resources :favorites, only: %i[create destroy index]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :image, presence: true
  validates :content, length: { in: 1..255 }
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :profile_picture, ProfilePictureUploader
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, length: { minimum: 6 }
  before_validation { email.downcase! }
  has_secure_password
  has_many :pictures
  has_many :favorites, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required

  private

  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorites = current_user.favorites
  end

  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_path, notice: "#{favorite.picture.user.name}さんの写真をお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_path, notice: "#{favorite.picture.user.name}さんの写真をお気に入り解除しました"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: %i[show edit update destroy]
  before_action :own_user, only: %i[edit update destroy]

  def index
    @pictures = Picture.all
  end

  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  def new
    @picture = Picture.new
  end

  def confirm
    @picture = current_user.pictures.build(picture_params)
    render :new if @picture.invalid?
  end

  def edit
  end

  def create
    @picture = current_user.pictures.build(picture_params)
    if params[:back]
      render :new
    else
      respond_to do |format|
        if @picture.save
          # PictureMailer.picture_mail(@picture).deliver
          format.html { redirect_to picture_url(@picture), notice: "画像を投稿しました！" }
          format.json { render :show, status: :created, location: @picture }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @picture.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to picture_url(@picture), notice: "画像を更新しました！" }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: "画像を削除しました。" }
      format.json { head :no_content }
    end
  end

  private

  def set_picture
    @picture = Picture.find(params[:id])
  end

  def picture_params
    params.require(:picture).permit(:image, :image_cache, :content)
  end

  def own_user
    redirect_to picture_path if current_user.id != @picture.user.id
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: %i[new create]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "ログインしました"
      redirect_to pictures_path
    else
      flash[:danger] = "ログインに失敗しました"
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = "ログアウトしました"
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: %i[new create]
  before_action :set_user, only: %i[show edit update]
  before_action :own_user, only: %i[edit update destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_url(@user), notice: "プロフィールを更新しました！"
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :profile_picture, :profile_picture_cache, :profile)
  end

  def own_user
    redirect_to user_path if current_user.id != @user.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == "new" || action_name == "create"
      confirm_pictures_path
    elsif action_name == "edit"
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
<h2>お気に入り一覧</h2>

<div class="row mb-5">
  <% if @favorites.present? %>
    <% @favorites.each do |favorite| %>
      <div class="col-md-4">
        <div class="card mb-4 shadow-sm card-body">
          <p class="card-text">
            <% if favorite.picture.user.profile_picture.present? %>
              <%= image_tag(favorite.picture.user.profile_picture.url, height: '30') %>
            <% else %>
            <% end %>
          <%= link_to favorite.picture.user.name, user_path(favorite.picture.user.id)%>
          </p>
          <p class="bd-placeholder-img card-img-top"><%= image_tag(favorite.picture.image.url, width: "100%") %></p>
          <div class="card-body">
            <p class="card-text"><%= favorite.picture.content %></p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <%= link_to '確認', picture_path(favorite.picture.id), type: "button", class: "btn btn-outline-secondary" %>
              </div>
            </div>
          </div>
        <small class="text-muted"><%= time_ago_in_words(favorite.picture.created_at) %></small>
        </div>
      </div>
    <% end %>
  <% else %>
    <p>登録しているお気に入りはありません。</p>
  <% end %>
</div>

<%= link_to '戻る', user_path(current_user), class: "mt-3 btn btn-outline-danger btn-lg" %>
<%= link_to 'Photos', pictures_path, class: "mt-3 ms-3 btn btn-outline-danger btn-lg" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photosharing</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header class="d-flex flex-column flex-md-row align-items-center bg-light bg-gradient p-3 px-md-4 mb-3 border-bottom shadow-sm">
    <h1 class="my-0 mr-md-auto font-weight-normal">Photosharing</h1>
    <nav class="my-4 my-md-2 mr-md-6">
    <% if logged_in? %>
      <%= image_tag(current_user.profile_picture.url, height: '50') if current_user.profile_picture && current_user.profile_picture.url %>
      <%= link_to "プロフィール", user_path(current_user.id), class: "btn btn-outline-danger btn-lg" %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete, class: "btn btn-outline-danger btn-lg" %>
    <% else %>
      <%= link_to "Sign up", new_user_path, class: "btn btn-outline-danger btn-lg" %>
      <%= link_to "Login", new_session_path, class: "btn btn-outline-danger btn-lg" %>
    <% end %>
    </nav>
  </header>
  <div class="container">
    <%= yield %>
  </div>
  <footer class="border-top mt-5">
    <div class="container px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <span class="fa-stack fa-lg">
              <i class="fas fa-circle fa-stack-2x"></i>
              <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
              </span>
            </li>
          </ul>
          <div class="small text-center text-muted fst-italic">Copyright &copy; Min 2023</div>
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <span class="fa-stack fa-lg">
              <i class="fas fa-circle fa-stack-2x"></i>
              <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
              </span>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </footer>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: picture, local: true, url: choose_new_or_edit) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
        <% picture.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mt-3 form-group">
    <h3><%= form.label :写真 %></h3>
    <%= image_tag(picture.image.url, width: "300") if picture.image && picture.image.url %>
    <div class ="mt-3">
      <%= form.file_field :image %>
      <%= form.hidden_field :image_cache %>
    </div>
  </div>

  <div class="field mt-3 form-group">
    <h3><%= form.label :テキスト %></h3>
    <%= form.text_area :content, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pictures/confirm.html.erb
<%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
  <h2>確認画面</h2>
  <p><%= image_tag(@picture.image.url, width: '350') if @picture.image && @picture.image.url %></p>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>
  <h3 class="mt-3">Content</h3>
  <p><%= @picture.content %></p>
  <div>
    <%= form.submit "投稿する", class: "btn btn-outline-danger" %>
  </div>

  <div class ="mt-3">
  <%= form.submit "戻る", name: "back", class: "btn btn-outline-danger" %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h2>編集画面</h2>

<%= render 'form', picture: @picture %>

<%= link_to '確認画面', @picture, class: "btn btn-outline-danger" %>
<%= link_to '戻る', pictures_path, class: "btn btn-outline-danger" %>

app/views/pictures/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Photos</h2>

<div class="row justify-content-end">
  <%= link_to 'New Post', new_picture_path, class: "mb-5 btn btn-danger btn-lg text-white" %>
</div>

<div class="row">
  <% @pictures.each do |picture| %>
    <div class="col-md-4">
      <div class="card mb-4 shadow-sm card-body">
        <p class="card-text">
          <% if picture.user.profile_picture.present? %>
            <%= image_tag(picture.user.profile_picture.url, height: '30') %>
          <% else %>
          <% end %>
          <%= link_to picture.user.name, user_path(picture.user.id)%>
        </p>
        <p class="bd-placeholder-img card-img-top"><%= image_tag(picture.image.url, width: "100%") %></p>
        <div class="card-body">
          <p class="card-text"><%= picture.content %></p>
          <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
              <% if picture.user_id == current_user.id %>
                <%= link_to '確認', picture, type: "button", class: "btn btn-outline-secondary" %>
                <%= link_to '編集', edit_picture_path(picture), type: "button", class: "btn btn-outline-secondary" %>
                <%= link_to '削除', picture, method: :delete, data: { confirm: '本当に削除していいですか？' }, type: "button", class: "btn btn-outline-secondary" %>
              <% else %>
                <%= link_to '確認', picture, type: "button", class: "btn btn-outline-secondary" %>
              <% end %>
            </div>
          </div>
        </div>
        <small class="text-muted"><%= time_ago_in_words(picture.created_at) %></small>
      </div>
    </div>
  <% end %>
</div>

app/views/pictures/new.html.erb
<h2>New Picture</h2>

<%= render 'form', picture: @picture %>

<%= link_to 'Back', pictures_path, class: "btn btn-outline-danger" %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<h5>写真:</h5>
<p><%= image_tag(@picture.image.url, width: '350') if @picture.image && @picture.image.url %></p>

<h5 class="mt-3">テキスト:</h5>
<p><%= @picture.content %></p>

<% unless @picture.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-secondary' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-warning' %>
  <% end %>
<% end %>

<% if @picture.user_id == current_user.id %>
  <%= link_to '編集', edit_picture_path(@picture), class: "btn btn-outline-danger" %>
  <%= link_to '戻る', pictures_path, class: "btn btn-outline-danger" %>
<% else %>
  <%= link_to '戻る', pictures_path, class: "btn btn-outline-danger" %>
<% end %>

app/views/users/edit.html.erb
<%= form_with(model: @user, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
        <% @user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<h2>プロフィール編集画面</h2>
  <div class="field mt-3 form-group">
    <h3><%= form.label :名前 %></h3>
    <%= form.text_area :name, class: "form-control" %>
  </div>

  <div class="field mt-3 form-group">
    <h3><%= form.label :プロフィール画像 %></h3>
    <%= image_tag(@user.profile_picture.url, width: "300") if @user.profile_picture && @user.profile_picture.url %>
    <div class ="mt-3">
      <%= form.file_field :profile_picture %>
      <%= form.hidden_field :profile_picture_cache %>
    </div>
  </div>

  <div class="field mt-3 form-group">
    <h3><%= form.label :プロフィール %></h3>
    <%= form.text_area :profile, class: "form-control"%>
  </div>

  <div class="field mt-3 form-group">
    <h3><%= form.label :パスワード %></h3>
    <%= form.text_area :password, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<div class ="mt-3">
  <%= link_to '戻る', user_path, class: "btn btn-outline-danger" %>
</div>
<% end %>

app/views/users/new.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
<% end %>

<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true, class: "form-group") do |f| %>
  <%= f.label :name, class: "mt-2" %>
  <%= f.text_field :name, class: "form-control mt-2" %>

  <%= f.label :email, class: "mt-2" %>
  <%= f.email_field :email, class: "form-control mt-2" %>

  <%= f.label :password, class: "mt-2" %>
  <%= f.password_field :password, class: "form-control mt-2" %>

  <%= f.label :password_confirmation, class: "mt-2" %>
  <%= f.password_field :password_confirmation, class: "form-control mt-2" %>

  <%= f.submit "Create my account", class: "form-control mt-5 btn btn-danger btn-lg" %>
<% end %>

app/views/users/show.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
<% end %>

<h2><%= @user.name %>のページ</h2>

<h5 class="mt-4">メールアドレス</h5>
<p><%= @user.email %></p>
<h5 class="mt-4">プロフィール画像</h5>
<p><%= image_tag(@user.profile_picture.url, width: '300') if @user.profile_picture && @user.profile_picture.url %></p>
<h5 class="mt-4">プロフィール</h5>
<p><%= @user.profile %></p>

<% if @user.id == current_user.id %>
  <%= link_to 'お気に入り一覧', favorites_path(@user), class: "mt-3 btn btn-outline-warning btn-lg" %>
  <%= link_to 'プロフィールを編集する', edit_user_path(@user), class: "mt-3 btn btn-outline-danger btn-lg" %>
  <%= link_to '戻る', pictures_path, class: "mt-3 ms-3 btn btn-outline-danger btn-lg" %>
<% else %>
  <%= link_to '戻る', pictures_path, class: "mt-3 btn btn-outline-danger btn-lg" %>
<% end %>